export function buildAiDetectionPrompt(text: string): string {
  const truncated = text.length > 40000 ? text.substring(0, 40000) + '...[TRUNCATED]' : text;
  
  return `You are an expert in AI-generated text detection. Analyze the following document and determine whether it was written by a human or generated by an AI language model.

Look for these AI indicators:
1. Uniform sentence length and rhythm (AI tends to produce very even sentence lengths)
2. Lack of personal voice, idiosyncrasies, or informal patterns
3. Overuse of transition words ("Furthermore", "Moreover", "In conclusion", "Additionally", "It is worth noting")
4. Perfect paragraph structure (intro sentence, body, conclusion in every paragraph)
5. Hedging language patterns ("It is important to note that...", "It should be noted that...")
6. Repetitive sentence structures (e.g., always starting with subject-verb)
7. Absence of specific examples, anecdotes, or domain-specific jargon
8. Overly balanced arguments (always "on one hand... on the other hand")
9. Generic summaries and conclusions that don't add specific value
10. Vocabulary uniformity (lack of register shifts or colloquialisms)

Look for these human indicators:
1. Irregular paragraph lengths and varying sentence complexity
2. Personal anecdotes or specific real-world examples
3. Domain-specific jargon or technical terminology used naturally
4. Occasional informal language or colloquialisms
5. Non-standard punctuation or stylistic choices
6. Unique voice or perspective
7. Typos, minor grammatical quirks, or stylistic inconsistencies

Return ONLY valid JSON with no markdown, no extra text:
{
  "ai_detection": {
    "overall_score": <0-100, where 0=certainly human, 100=certainly AI>,
    "confidence": "low|medium|high",
    "verdict": "likely_human|mixed|likely_ai",
    "signals": [
      {
        "pattern": "<pattern name like uniform_sentence_length>",
        "description": "<specific observation>",
        "severity": "low|medium|high",
        "evidence": "<direct quote or excerpt from document>"
      }
    ],
    "human_indicators": ["<indicator 1>", "<indicator 2>"],
    "ai_indicators": ["<indicator 1>", "<indicator 2>"],
    "summary": "<one paragraph assessment>"
  }
}

DOCUMENT TEXT:
${truncated}`;
}
