export function generateHtmlReport(report: any, fileName: string): string {
  const date = new Date().toLocaleString();
  const operations = (report.operations || []).map((op: string) =>
    '<li>' + escapeHtml(op) + '</li>'
  ).join('');

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>Mindorion Sanitization Report</title>',
    '<style>',
    'body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #333; }',
    'h1 { color: #1a1a2e; border-bottom: 3px solid #4a90d9; padding-bottom: 10px; }',
    'h2 { color: #2c3e50; margin-top: 30px; }',
    '.summary { background: #f8f9fa; border-radius: 8px; padding: 20px; margin: 20px 0; }',
    '.stat { display: inline-block; text-align: center; margin: 0 20px; }',
    '.stat-value { font-size: 2em; font-weight: bold; color: #4a90d9; }',
    '.stat-label { font-size: 0.85em; color: #666; }',
    '.operations { list-style: none; padding: 0; }',
    '.operations li { padding: 8px 12px; margin: 5px 0; background: #e8f4f8; border-left: 4px solid #4a90d9; border-radius: 0 4px 4px 0; }',
    '.badge { display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 0.8em; font-weight: bold; }',
    '.badge-success { background: #d4edda; color: #155724; }',
    'footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 0.85em; text-align: center; }',
    '</style>',
    '</head>',
    '<body>',
    '<h1>Mindorion Sanitization Report</h1>',
    '<div class="summary">',
    '<h2>Summary</h2>',
    '<div class="stat"><div class="stat-value">' + (report.removedItems || 0) + '</div><div class="stat-label">Items Cleaned</div></div>',
    '<div class="stat"><div class="stat-value">' + (report.operations ? report.operations.length : 0) + '</div><div class="stat-label">Operations</div></div>',
    '</div>',
    '<h2>Document</h2>',
    '<p><strong>File:</strong> ' + escapeHtml(fileName) + '</p>',
    '<p><strong>Processed:</strong> ' + date + '</p>',
    '<h2>Cleaning Operations</h2>',
    operations ? '<ul class="operations">' + operations + '</ul>' : '<p>No cleaning operations were performed.</p>',
    '<footer>Generated by Mindorion Document Intelligence Engine &mdash; ' + date + '</footer>',
    '</body>',
    '</html>',
  ].join('\n');
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
